# Generated by Django 4.2.30 on 2026-10-03 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'conversations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('SYSTEM', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('attachment_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('sent_at', models.DateTimeField()),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'messages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConversationMember',
            fields=[
                ('conversation', models.ForeignKey(db_column='conversation_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='members', serialize=False, to='messaging.conversation')),
                ('joined_at', models.DateTimeField()),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'conversation_members',
                'managed': False,
            },
        ),
    ]
