# Generated by Django 4.2.30 on 2026-10-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='OPEN', max_length=20)),
                ('resolution_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reports',
                'managed': False,
            },
        ),
    ]
