-- Passbook v1.2 lite schema-only DDL.
-- Requires MySQL 8.0.16+ (or compatible MariaDB) for enforced CHECK constraints.
-- Uses utf8mb4_unicode_ci for compatibility with XAMPP MariaDB.
-- Creates 41 tables: a reduced commerce/social schema plus dedicated book reservations and OTP verification.
-- No database name, database creation, seed data, migration, or DROP statements.
-- Application validation must enforce polymorphic target exclusivity and cross-FK consistency.
-- CHECK constraints touching FK columns are omitted because MySQL restricts referential-action columns in CHECK expressions.
-- Amounts use VND DECIMAL(19,4); fee rates are ratios from 0 through 1.
SET NAMES utf8mb4;

CREATE TABLE `universities` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `code` VARCHAR(50) NOT NULL,
  `address` VARCHAR(500) NULL DEFAULT NULL,
  `website` VARCHAR(2048) NULL DEFAULT NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  CONSTRAINT `uq_universities_1` UNIQUE (`code`),
  KEY `ix_universities_1` (`status`, `name`)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `faculties` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `university_id` BIGINT UNSIGNED NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `code` VARCHAR(50) NOT NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  CONSTRAINT `uq_faculties_1` UNIQUE (`university_id`, `code`),
  CONSTRAINT `uq_faculties_2` UNIQUE (`id`, `university_id`),
  KEY `ix_faculties_1` (`university_id`, `status`, `name`),
  CONSTRAINT `fk_faculties_1` FOREIGN KEY (`university_id`) REFERENCES `universities` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `majors` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `faculty_id` BIGINT UNSIGNED NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `code` VARCHAR(50) NOT NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  CONSTRAINT `uq_majors_1` UNIQUE (`faculty_id`, `code`),
  CONSTRAINT `uq_majors_2` UNIQUE (`id`, `faculty_id`),
  KEY `ix_majors_1` (`faculty_id`, `status`, `name`),
  CONSTRAINT `fk_majors_1` FOREIGN KEY (`faculty_id`) REFERENCES `faculties` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `users` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(254) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `full_name` VARCHAR(150) NOT NULL,
  `phone` VARCHAR(30) NULL DEFAULT NULL,
  `avatar_url` VARCHAR(2048) NULL DEFAULT NULL,
  `role` VARCHAR(20) NOT NULL,
  `status` VARCHAR(20) NOT NULL,
  `university_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `faculty_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `major_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  CONSTRAINT `uq_users_1` UNIQUE (`email`),
  KEY `ix_users_1` (`university_id`, `status`),
  KEY `ix_users_2` (`faculty_id`),
  KEY `ix_users_3` (`major_id`),
  KEY `ix_users_4` (`faculty_id`, `university_id`),
  KEY `ix_users_5` (`major_id`, `faculty_id`),
  CONSTRAINT `fk_users_1` FOREIGN KEY (`university_id`) REFERENCES `universities` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_users_2` FOREIGN KEY (`faculty_id`, `university_id`) REFERENCES `faculties` (`id`, `university_id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_users_3` FOREIGN KEY (`major_id`, `faculty_id`) REFERENCES `majors` (`id`, `faculty_id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `otp_verifications` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `channel` ENUM('EMAIL', 'PHONE') NOT NULL,
  `purpose` ENUM('REGISTER', 'LOGIN', 'FORGOT_PASSWORD', 'CHANGE_EMAIL', 'CHANGE_PHONE') NOT NULL,
  `target` VARCHAR(255) NOT NULL,
  `otp_hash` VARCHAR(255) NOT NULL,
  `expires_at` DATETIME NOT NULL,
  `verified_at` DATETIME NULL DEFAULT NULL,
  `attempt_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `resend_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `status` ENUM('PENDING', 'VERIFIED', 'EXPIRED', 'BLOCKED') NOT NULL DEFAULT 'PENDING',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_otp_target_purpose_status` (`target`, `purpose`, `status`),
  KEY `idx_otp_user_purpose_status` (`user_id`, `purpose`, `status`),
  KEY `idx_otp_expires_at` (`expires_at`),
  CONSTRAINT `fk_otp_verifications_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `user_addresses` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `recipient_name` VARCHAR(150) NOT NULL,
  `phone` VARCHAR(30) NOT NULL,
  `address_line` VARCHAR(500) NOT NULL,
  `ward` VARCHAR(150) NOT NULL,
  `district` VARCHAR(150) NOT NULL,
  `city` VARCHAR(150) NOT NULL,
  `postal_code` VARCHAR(30) NULL DEFAULT NULL,
  `is_default` BOOLEAN NOT NULL DEFAULT FALSE,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `default_address_user_key` BIGINT UNSIGNED GENERATED ALWAYS AS (CASE WHEN `is_default` = 1 THEN `user_id` ELSE NULL END) STORED,
  PRIMARY KEY (`id`),
  CONSTRAINT `uq_user_addresses_1` UNIQUE (`default_address_user_key`),
  KEY `ix_user_addresses_1` (`user_id`, `is_default`),
  CONSTRAINT `ck_user_addresses_1` CHECK (`is_default` IN (0,1)),
  CONSTRAINT `fk_user_addresses_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `user_violations` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `violation_type` VARCHAR(50) NOT NULL,
  `reason` VARCHAR(255) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `severity` VARCHAR(20) NOT NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'OPEN',
  `expires_at` DATETIME(3) NULL DEFAULT NULL,
  `created_by` BIGINT UNSIGNED NULL DEFAULT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `resolved_at` DATETIME(3) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `ix_user_violations_1` (`user_id`, `status`, `created_at`),
  KEY `ix_user_violations_2` (`status`, `severity`, `created_at`),
  KEY `ix_user_violations_3` (`created_by`),
  CONSTRAINT `fk_user_violations_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_user_violations_2` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `subjects` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `code` VARCHAR(50) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `credits` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  CONSTRAINT `uq_subjects_1` UNIQUE (`code`),
  KEY `ix_subjects_1` (`status`, `name`),
  CONSTRAINT `ck_subjects_1` CHECK (`credits` IS NULL OR `credits` > 0)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `categories` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `parent_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `name` VARCHAR(150) NOT NULL,
  `slug` VARCHAR(180) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  CONSTRAINT `uq_categories_1` UNIQUE (`slug`),
  KEY `ix_categories_1` (`parent_id`, `status`, `name`),
  CONSTRAINT `fk_categories_1` FOREIGN KEY (`parent_id`) REFERENCES `categories` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `languages` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `code` VARCHAR(20) NOT NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  CONSTRAINT `uq_languages_1` UNIQUE (`code`),
  KEY `ix_languages_1` (`status`, `name`)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `book_works` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(500) NOT NULL,
  `subtitle` VARCHAR(500) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `author_name` VARCHAR(500) NULL DEFAULT NULL,
  `publisher_name` VARCHAR(255) NULL DEFAULT NULL,
  `category_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `created_by` BIGINT UNSIGNED NOT NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `ix_book_works_1` (`status`, `created_at`, `id`),
  KEY `ix_book_works_2` (`category_id`, `status`, `created_at`),
  KEY `ix_book_works_3` (`created_by`),
  CONSTRAINT `fk_book_works_1` FOREIGN KEY (`category_id`) REFERENCES `categories` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_book_works_2` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `book_work_subjects` (
  `book_work_id` BIGINT UNSIGNED NOT NULL,
  `subject_id` BIGINT UNSIGNED NOT NULL,
  `is_primary` BOOLEAN NOT NULL DEFAULT FALSE,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `primary_subject_work_key` BIGINT UNSIGNED GENERATED ALWAYS AS (CASE WHEN `is_primary` = 1 THEN `book_work_id` ELSE NULL END) STORED,
  PRIMARY KEY (`book_work_id`, `subject_id`),
  CONSTRAINT `uq_book_work_subjects_1` UNIQUE (`primary_subject_work_key`),
  KEY `ix_book_work_subjects_1` (`subject_id`, `book_work_id`),
  CONSTRAINT `ck_book_work_subjects_1` CHECK (`is_primary` IN (0,1)),
  CONSTRAINT `fk_book_work_subjects_1` FOREIGN KEY (`book_work_id`) REFERENCES `book_works` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_book_work_subjects_2` FOREIGN KEY (`subject_id`) REFERENCES `subjects` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `book_editions` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `book_work_id` BIGINT UNSIGNED NOT NULL,
  `edition_name` VARCHAR(100) NULL DEFAULT NULL,
  `edition_number` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `publisher_name` VARCHAR(255) NULL DEFAULT NULL,
  `publication_year` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `publication_date` DATE NULL DEFAULT NULL,
  `page_count` INT UNSIGNED NULL DEFAULT NULL,
  `format` VARCHAR(30) NULL DEFAULT NULL,
  `language_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `ix_book_editions_1` (`book_work_id`, `publication_year`),
  KEY `ix_book_editions_2` (`language_id`),
  CONSTRAINT `ck_book_editions_1` CHECK (`edition_number` IS NULL OR `edition_number` > 0),
  CONSTRAINT `ck_book_editions_2` CHECK (`page_count` IS NULL OR `page_count` > 0),
  CONSTRAINT `fk_book_editions_1` FOREIGN KEY (`book_work_id`) REFERENCES `book_works` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_book_editions_2` FOREIGN KEY (`language_id`) REFERENCES `languages` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `book_identifiers` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `book_edition_id` BIGINT UNSIGNED NOT NULL,
  `identifier_type` VARCHAR(30) NOT NULL,
  `identifier_value` VARCHAR(100) NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  CONSTRAINT `uq_book_identifiers_1` UNIQUE (`identifier_type`, `identifier_value`),
  KEY `ix_book_identifiers_1` (`book_edition_id`),
  CONSTRAINT `ck_book_identifiers_1` CHECK (CHAR_LENGTH(TRIM(`identifier_type`)) > 0),
  CONSTRAINT `ck_book_identifiers_2` CHECK (CHAR_LENGTH(TRIM(`identifier_value`)) > 0),
  CONSTRAINT `fk_book_identifiers_1` FOREIGN KEY (`book_edition_id`) REFERENCES `book_editions` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `books` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `book_edition_id` BIGINT UNSIGNED NOT NULL,
  `owner_id` BIGINT UNSIGNED NOT NULL,
  `condition_label` VARCHAR(30) NOT NULL,
  `condition_description` TEXT NULL DEFAULT NULL,
  `acquisition_type` VARCHAR(30) NULL DEFAULT NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'AVAILABLE',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `ix_books_1` (`status`, `created_at`, `id`),
  KEY `ix_books_2` (`owner_id`, `status`, `created_at`, `id`),
  KEY `ix_books_3` (`book_edition_id`),
  CONSTRAINT `ck_books_1` CHECK (`status` IN ('AVAILABLE','RESERVED','ON_LOAN','SOLD','UNAVAILABLE')),
  CONSTRAINT `fk_books_1` FOREIGN KEY (`book_edition_id`) REFERENCES `book_editions` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_books_2` FOREIGN KEY (`owner_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `book_images` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `book_id` BIGINT UNSIGNED NOT NULL,
  `image_url` VARCHAR(2048) NOT NULL,
  `cloudinary_public_id` VARCHAR(255) NULL DEFAULT NULL,
  `is_primary` BOOLEAN NOT NULL DEFAULT FALSE,
  `sort_order` INT UNSIGNED NOT NULL DEFAULT 0,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `primary_image_book_key` BIGINT UNSIGNED GENERATED ALWAYS AS (CASE WHEN `is_primary` = 1 THEN `book_id` ELSE NULL END) STORED,
  PRIMARY KEY (`id`),
  CONSTRAINT `uq_book_images_1` UNIQUE (`primary_image_book_key`),
  KEY `ix_book_images_1` (`book_id`, `is_primary`, `sort_order`),
  CONSTRAINT `ck_book_images_1` CHECK (`sort_order` >= 0),
  CONSTRAINT `ck_book_images_2` CHECK (`is_primary` IN (0,1)),
  CONSTRAINT `fk_book_images_1` FOREIGN KEY (`book_id`) REFERENCES `books` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `sale_listings` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `book_id` BIGINT UNSIGNED NOT NULL,
  `seller_id` BIGINT UNSIGNED NOT NULL,
  `title` VARCHAR(500) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `price` DECIMAL(19,4) NOT NULL,
  `currency` CHAR(3) NOT NULL DEFAULT 'VND',
  `status` VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
  `published_at` DATETIME(3) NULL DEFAULT NULL,
  `expires_at` DATETIME(3) NULL DEFAULT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `active_sale_book_key` BIGINT UNSIGNED GENERATED ALWAYS AS (CASE WHEN `status` IN ('ACTIVE','RESERVED') THEN `book_id` ELSE NULL END) STORED,
  PRIMARY KEY (`id`),
  CONSTRAINT `uq_sale_listings_1` UNIQUE (`active_sale_book_key`),
  KEY `ix_sale_listings_1` (`seller_id`, `status`, `created_at`, `id`),
  KEY `ix_sale_listings_2` (`status`, `price`, `id`),
  KEY `ix_sale_listings_3` (`status`, `created_at`, `id`),
  KEY `ix_sale_listings_4` (`book_id`),
  CONSTRAINT `ck_sale_listings_1` CHECK (`price` > 0),
  CONSTRAINT `ck_sale_listings_2` CHECK (`currency` = 'VND'),
  CONSTRAINT `ck_sale_listings_3` CHECK (`status` IN ('DRAFT','PENDING','ACTIVE','REJECTED','RESERVED','SOLD','CLOSED','EXPIRED')),
  CONSTRAINT `ck_sale_listings_4` CHECK (`expires_at` IS NULL OR `published_at` IS NULL OR `expires_at` > `published_at`),
  CONSTRAINT `fk_sale_listings_1` FOREIGN KEY (`book_id`) REFERENCES `books` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_sale_listings_2` FOREIGN KEY (`seller_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `lend_listings` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `book_id` BIGINT UNSIGNED NOT NULL,
  `lender_id` BIGINT UNSIGNED NOT NULL,
  `title` VARCHAR(500) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
  `deposit_amount` DECIMAL(19,4) NULL DEFAULT NULL,
  `rental_fee` DECIMAL(19,4) NOT NULL,
  `currency` CHAR(3) NOT NULL DEFAULT 'VND',
  `published_at` DATETIME(3) NULL DEFAULT NULL,
  `expires_at` DATETIME(3) NULL DEFAULT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `active_lend_book_key` BIGINT UNSIGNED GENERATED ALWAYS AS (CASE WHEN `status` IN ('ACTIVE','RESERVED','ON_LOAN') THEN `book_id` ELSE NULL END) STORED,
  PRIMARY KEY (`id`),
  CONSTRAINT `uq_lend_listings_1` UNIQUE (`active_lend_book_key`),
  KEY `ix_lend_listings_1` (`lender_id`, `status`, `created_at`, `id`),
  KEY `ix_lend_listings_2` (`status`, `rental_fee`, `id`),
  KEY `ix_lend_listings_3` (`status`, `created_at`, `id`),
  KEY `ix_lend_listings_4` (`book_id`),
  CONSTRAINT `ck_lend_listings_1` CHECK (`rental_fee` >= 0),
  CONSTRAINT `ck_lend_listings_2` CHECK (`deposit_amount` IS NULL OR `deposit_amount` >= 0),
  CONSTRAINT `ck_lend_listings_3` CHECK (`currency` = 'VND'),
  CONSTRAINT `ck_lend_listings_4` CHECK (`status` IN ('DRAFT','ACTIVE','RESERVED','ON_LOAN','CLOSED','EXPIRED')),
  CONSTRAINT `fk_lend_listings_1` FOREIGN KEY (`book_id`) REFERENCES `books` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_lend_listings_2` FOREIGN KEY (`lender_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `borrow_terms` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `lend_listing_id` BIGINT UNSIGNED NOT NULL,
  `max_days` SMALLINT UNSIGNED NOT NULL,
  `late_fee_per_day` DECIMAL(19,4) NULL DEFAULT NULL,
  `deposit_required` BOOLEAN NOT NULL DEFAULT FALSE,
  `shipping_paid_by` VARCHAR(20) NOT NULL,
  `return_method` VARCHAR(30) NOT NULL,
  `notes` TEXT NULL DEFAULT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  CONSTRAINT `uq_borrow_terms_1` UNIQUE (`lend_listing_id`),
  CONSTRAINT `ck_borrow_terms_1` CHECK (`max_days` > 0),
  CONSTRAINT `ck_borrow_terms_2` CHECK (`late_fee_per_day` IS NULL OR `late_fee_per_day` >= 0),
  CONSTRAINT `ck_borrow_terms_3` CHECK (`deposit_required` IN (0,1)),
  CONSTRAINT `fk_borrow_terms_1` FOREIGN KEY (`lend_listing_id`) REFERENCES `lend_listings` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `book_requests` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `request_type` VARCHAR(20) NOT NULL,
  `book_work_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `category_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `title_keyword` VARCHAR(500) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `budget_max` DECIMAL(19,4) NULL DEFAULT NULL,
  `asking_price` DECIMAL(19,4) NULL DEFAULT NULL,
  `currency` CHAR(3) NULL DEFAULT NULL,
  `condition_preference` VARCHAR(30) NULL DEFAULT NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'OPEN',
  `expires_at` DATETIME(3) NULL DEFAULT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `ix_book_requests_1` (`user_id`, `status`, `created_at`, `id`),
  KEY `ix_book_requests_2` (`request_type`, `status`, `expires_at`),
  KEY `ix_book_requests_3` (`category_id`, `status`, `created_at`),
  KEY `ix_book_requests_4` (`book_work_id`, `status`),
  CONSTRAINT `ck_book_requests_1` CHECK (`request_type` IN ('BUY','BORROW','SELL_INTENT')),
  CONSTRAINT `ck_book_requests_3` CHECK ((`request_type` IN ('BUY','BORROW') AND `asking_price` IS NULL) OR (`request_type` = 'SELL_INTENT' AND `budget_max` IS NULL)),
  CONSTRAINT `ck_book_requests_4` CHECK ((`budget_max` IS NULL OR `budget_max` >= 0) AND (`asking_price` IS NULL OR `asking_price` >= 0)),
  CONSTRAINT `ck_book_requests_5` CHECK ((`currency` IS NULL OR `currency` = 'VND') AND ((`budget_max` IS NULL AND `asking_price` IS NULL) OR `currency` = 'VND')),
  CONSTRAINT `fk_book_requests_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_book_requests_2` FOREIGN KEY (`book_work_id`) REFERENCES `book_works` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_book_requests_3` FOREIGN KEY (`category_id`) REFERENCES `categories` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `request_interests` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `request_id` BIGINT UNSIGNED NOT NULL,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `note` TEXT NULL DEFAULT NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  CONSTRAINT `uq_request_interests_1` UNIQUE (`request_id`, `user_id`),
  KEY `ix_request_interests_1` (`request_id`, `status`, `created_at`),
  KEY `ix_request_interests_2` (`user_id`, `status`, `created_at`),
  CONSTRAINT `fk_request_interests_1` FOREIGN KEY (`request_id`) REFERENCES `book_requests` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_request_interests_2` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `request_matches` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `request_id` BIGINT UNSIGNED NOT NULL,
  `matched_request_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `sale_listing_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `lend_listing_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `match_type` VARCHAR(20) NOT NULL,
  `score` DECIMAL(6,5) NULL DEFAULT NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'SUGGESTED',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `ix_request_matches_1` (`request_id`, `status`, `created_at`),
  KEY `ix_request_matches_2` (`sale_listing_id`, `status`),
  KEY `ix_request_matches_3` (`lend_listing_id`, `status`),
  KEY `ix_request_matches_4` (`matched_request_id`, `status`),
  CONSTRAINT `ck_request_matches_2` CHECK (`score` IS NULL OR (`score` >= 0 AND `score` <= 1)),
  CONSTRAINT `fk_request_matches_1` FOREIGN KEY (`request_id`) REFERENCES `book_requests` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_request_matches_2` FOREIGN KEY (`sale_listing_id`) REFERENCES `sale_listings` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_request_matches_3` FOREIGN KEY (`lend_listing_id`) REFERENCES `lend_listings` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_request_matches_4` FOREIGN KEY (`matched_request_id`) REFERENCES `book_requests` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `carts` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `active_cart_user_key` BIGINT UNSIGNED GENERATED ALWAYS AS (CASE WHEN `status` = 'ACTIVE' THEN `user_id` ELSE NULL END) STORED,
  PRIMARY KEY (`id`),
  CONSTRAINT `uq_carts_1` UNIQUE (`active_cart_user_key`),
  KEY `ix_carts_1` (`user_id`, `status`, `updated_at`),
  CONSTRAINT `ck_carts_1` CHECK (`status` IN ('ACTIVE','CHECKED_OUT','ABANDONED')),
  CONSTRAINT `fk_carts_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `cart_items` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_id` BIGINT UNSIGNED NOT NULL,
  `sale_listing_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `lend_listing_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `unit_price` DECIMAL(19,4) NOT NULL,
  `currency` CHAR(3) NOT NULL DEFAULT 'VND',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  CONSTRAINT `uq_cart_items_1` UNIQUE (`cart_id`, `sale_listing_id`),
  CONSTRAINT `uq_cart_items_2` UNIQUE (`cart_id`, `lend_listing_id`),
  KEY `ix_cart_items_1` (`cart_id`, `created_at`, `id`),
  KEY `ix_cart_items_2` (`sale_listing_id`),
  KEY `ix_cart_items_3` (`lend_listing_id`),
  CONSTRAINT `ck_cart_items_2` CHECK (`unit_price` >= 0),
  CONSTRAINT `ck_cart_items_3` CHECK (`currency` = 'VND'),
  CONSTRAINT `fk_cart_items_1` FOREIGN KEY (`cart_id`) REFERENCES `carts` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_cart_items_2` FOREIGN KEY (`sale_listing_id`) REFERENCES `sale_listings` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_cart_items_3` FOREIGN KEY (`lend_listing_id`) REFERENCES `lend_listings` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `checkout_groups` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `checkout_code` VARCHAR(64) NOT NULL,
  `idempotency_key` VARCHAR(128) NOT NULL,
  `cart_id` BIGINT UNSIGNED NOT NULL,
  `buyer_id` BIGINT UNSIGNED NOT NULL,
  `status` VARCHAR(20) NOT NULL,
  `currency` CHAR(3) NOT NULL DEFAULT 'VND',
  `subtotal` DECIMAL(19,4) NOT NULL,
  `shipping_total` DECIMAL(19,4) NOT NULL DEFAULT 0,
  `discount_total` DECIMAL(19,4) NOT NULL DEFAULT 0,
  `total_amount` DECIMAL(19,4) NOT NULL,
  `shipping_address_snapshot` JSON NOT NULL,
  `pricing_snapshot` JSON NOT NULL,
  `reservation_expires_at` DATETIME(3) NULL DEFAULT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `completed_at` DATETIME(3) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `uq_checkout_groups_1` UNIQUE (`checkout_code`),
  CONSTRAINT `uq_checkout_groups_2` UNIQUE (`buyer_id`, `idempotency_key`),
  KEY `ix_checkout_groups_1` (`buyer_id`, `status`, `created_at`, `id`),
  KEY `ix_checkout_groups_2` (`cart_id`, `created_at`),
  KEY `ix_checkout_groups_3` (`status`, `reservation_expires_at`),
  CONSTRAINT `ck_checkout_groups_1` CHECK (`currency` = 'VND'),
  CONSTRAINT `ck_checkout_groups_2` CHECK (`subtotal` >= 0 AND `shipping_total` >= 0 AND `discount_total` >= 0 AND `total_amount` >= 0),
  CONSTRAINT `ck_checkout_groups_3` CHECK (`reservation_expires_at` IS NULL OR `reservation_expires_at` > `created_at`),
  CONSTRAINT `fk_checkout_groups_1` FOREIGN KEY (`cart_id`) REFERENCES `carts` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_checkout_groups_2` FOREIGN KEY (`buyer_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `orders` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_code` VARCHAR(64) NOT NULL,
  `checkout_group_id` BIGINT UNSIGNED NOT NULL,
  `buyer_id` BIGINT UNSIGNED NOT NULL,
  `seller_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `order_type` VARCHAR(20) NOT NULL,
  `status` VARCHAR(30) NOT NULL DEFAULT 'PENDING_PAYMENT',
  `currency` CHAR(3) NOT NULL DEFAULT 'VND',
  `subtotal` DECIMAL(19,4) NOT NULL,
  `shipping_fee` DECIMAL(19,4) NOT NULL DEFAULT 0,
  `discount_amount` DECIMAL(19,4) NOT NULL DEFAULT 0,
  `total_amount` DECIMAL(19,4) NOT NULL,
  `shipping_address_snapshot` JSON NOT NULL,
  `pricing_snapshot` JSON NOT NULL,
  `note` TEXT NULL DEFAULT NULL,
  `placed_at` DATETIME(3) NULL DEFAULT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `completed_at` DATETIME(3) NULL DEFAULT NULL,
  `sale_seller_key` BIGINT UNSIGNED GENERATED ALWAYS AS (CASE WHEN `order_type` = 'SALE' THEN `seller_id` ELSE NULL END) STORED,
  PRIMARY KEY (`id`),
  CONSTRAINT `uq_orders_1` UNIQUE (`order_code`),
  CONSTRAINT `uq_orders_2` UNIQUE (`checkout_group_id`, `sale_seller_key`),
  KEY `ix_orders_1` (`buyer_id`, `status`, `created_at`, `id`),
  KEY `ix_orders_2` (`seller_id`, `status`, `created_at`, `id`),
  KEY `ix_orders_3` (`checkout_group_id`, `order_type`),
  KEY `ix_orders_4` (`order_type`, `status`, `created_at`, `id`),
  CONSTRAINT `ck_orders_status` CHECK (`status` IN ('PENDING_PAYMENT','CONFIRMED','PROCESSING','COMPLETED','CANCELLED','DISPUTED')),
  CONSTRAINT `ck_orders_currency` CHECK (`currency` = 'VND'),
  CONSTRAINT `ck_orders_amounts` CHECK (`subtotal` >= 0 AND `shipping_fee` >= 0 AND `discount_amount` >= 0 AND `total_amount` >= 0),
  CONSTRAINT `fk_orders_1` FOREIGN KEY (`checkout_group_id`) REFERENCES `checkout_groups` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_orders_2` FOREIGN KEY (`buyer_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_orders_3` FOREIGN KEY (`seller_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `sale_order_items` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_id` BIGINT UNSIGNED NOT NULL,
  `sale_listing_id` BIGINT UNSIGNED NOT NULL,
  `book_id` BIGINT UNSIGNED NOT NULL,
  `seller_id` BIGINT UNSIGNED NOT NULL,
  `title_snapshot` VARCHAR(500) NOT NULL,
  `condition_snapshot` VARCHAR(30) NOT NULL,
  `unit_price` DECIMAL(19,4) NOT NULL,
  `discount_allocated` DECIMAL(19,4) NOT NULL DEFAULT 0,
  `quantity` SMALLINT UNSIGNED NOT NULL DEFAULT 1,
  `subtotal` DECIMAL(19,4) NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  CONSTRAINT `uq_sale_order_items_1` UNIQUE (`order_id`, `sale_listing_id`),
  KEY `ix_sale_order_items_1` (`order_id`, `seller_id`),
  KEY `ix_sale_order_items_2` (`seller_id`, `created_at`),
  KEY `ix_sale_order_items_3` (`sale_listing_id`),
  KEY `ix_sale_order_items_4` (`book_id`),
  CONSTRAINT `ck_sale_order_items_1` CHECK (`quantity` = 1),
  CONSTRAINT `fk_sale_order_items_1` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_sale_order_items_2` FOREIGN KEY (`sale_listing_id`) REFERENCES `sale_listings` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_sale_order_items_3` FOREIGN KEY (`book_id`) REFERENCES `books` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_sale_order_items_4` FOREIGN KEY (`seller_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `borrow_orders` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_id` BIGINT UNSIGNED NOT NULL,
  `checkout_group_id` BIGINT UNSIGNED NOT NULL,
  `lend_listing_id` BIGINT UNSIGNED NOT NULL,
  `lender_id` BIGINT UNSIGNED NOT NULL,
  `borrower_id` BIGINT UNSIGNED NOT NULL,
  `status` VARCHAR(30) NOT NULL DEFAULT 'PENDING',
  `borrow_terms_snapshot` JSON NOT NULL,
  `expected_start_at` DATETIME(3) NULL DEFAULT NULL,
  `expected_return_at` DATETIME(3) NULL DEFAULT NULL,
  `actual_start_at` DATETIME(3) NULL DEFAULT NULL,
  `actual_return_at` DATETIME(3) NULL DEFAULT NULL,
  `rental_fee` DECIMAL(19,4) NOT NULL,
  `deposit_amount` DECIMAL(19,4) NOT NULL DEFAULT 0,
  `deposit_refunded_amount` DECIMAL(19,4) NOT NULL DEFAULT 0,
  `deposit_forfeited_amount` DECIMAL(19,4) NOT NULL DEFAULT 0,
  `late_fee_amount` DECIMAL(19,4) NOT NULL DEFAULT 0,
  `return_requested_by` BIGINT UNSIGNED NULL DEFAULT NULL,
  `return_status` VARCHAR(20) NULL DEFAULT NULL,
  `return_method` VARCHAR(30) NULL DEFAULT NULL,
  `return_tracking_code` VARCHAR(100) NULL DEFAULT NULL,
  `return_requested_at` DATETIME(3) NULL DEFAULT NULL,
  `return_approved_at` DATETIME(3) NULL DEFAULT NULL,
  `return_notes` TEXT NULL DEFAULT NULL,
  `currency` CHAR(3) NOT NULL DEFAULT 'VND',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  CONSTRAINT `uq_borrow_orders_1` UNIQUE (`order_id`),
  CONSTRAINT `uq_borrow_orders_2` UNIQUE (`checkout_group_id`, `lend_listing_id`),
  CONSTRAINT `uq_borrow_orders_3` UNIQUE (`id`, `order_id`),
  KEY `ix_borrow_orders_1` (`lender_id`, `status`, `expected_return_at`),
  KEY `ix_borrow_orders_2` (`borrower_id`, `status`, `created_at`),
  KEY `ix_borrow_orders_3` (`lend_listing_id`, `status`),
  KEY `ix_borrow_orders_4` (`return_requested_by`),
  CONSTRAINT `ck_borrow_orders_1` CHECK (`rental_fee` >= 0 AND `deposit_amount` >= 0 AND `deposit_refunded_amount` >= 0 AND `deposit_forfeited_amount` >= 0 AND `late_fee_amount` >= 0),
  CONSTRAINT `ck_borrow_orders_2` CHECK (`deposit_refunded_amount` + `deposit_forfeited_amount` <= `deposit_amount`),
  CONSTRAINT `ck_borrow_orders_3` CHECK (`expected_start_at` IS NULL OR `expected_return_at` IS NULL OR `expected_return_at` > `expected_start_at`),
  CONSTRAINT `ck_borrow_orders_4` CHECK (`actual_return_at` IS NULL OR (`actual_start_at` IS NOT NULL AND `actual_return_at` >= `actual_start_at`)),
  CONSTRAINT `ck_borrow_orders_status` CHECK (`status` IN ('PENDING','CONFIRMED','REJECTED','READY_FOR_PICKUP','ACTIVE','RETURN_REQUESTED','RETURNED','CANCELLED','OVERDUE','DISPUTED','COMPLETED')),
  CONSTRAINT `ck_borrow_orders_5` CHECK (`currency` = 'VND'),
  CONSTRAINT `fk_borrow_orders_1` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_borrow_orders_2` FOREIGN KEY (`checkout_group_id`) REFERENCES `checkout_groups` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_borrow_orders_3` FOREIGN KEY (`lend_listing_id`) REFERENCES `lend_listings` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_borrow_orders_4` FOREIGN KEY (`lender_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_borrow_orders_5` FOREIGN KEY (`borrower_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_borrow_orders_6` FOREIGN KEY (`return_requested_by`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `payments` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `checkout_group_id` BIGINT UNSIGNED NOT NULL,
  `order_id` BIGINT UNSIGNED NOT NULL,
  `payer_id` BIGINT UNSIGNED NOT NULL,
  `provider` VARCHAR(50) NOT NULL,
  `payment_method` VARCHAR(30) NOT NULL,
  `provider_transaction_code` VARCHAR(150) NULL DEFAULT NULL,
  `payment_purpose` VARCHAR(30) NOT NULL DEFAULT 'CHECKOUT',
  `amount` DECIMAL(19,4) NOT NULL COMMENT 'Gross amount charged for this order',
  `platform_fee_rate` DECIMAL(9,6) NOT NULL DEFAULT 0 COMMENT 'Platform fee ratio from 0 to 1',
  `platform_fee` DECIMAL(19,4) NOT NULL DEFAULT 0,
  `seller_amount` DECIMAL(19,4) NOT NULL,
  `currency` CHAR(3) NOT NULL DEFAULT 'VND',
  `status` VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  `idempotency_key` VARCHAR(128) NOT NULL,
  `paid_at` DATETIME(3) NULL DEFAULT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  CONSTRAINT `uq_payments_1` UNIQUE (`provider`, `provider_transaction_code`),
  CONSTRAINT `uq_payments_2` UNIQUE (`provider`, `idempotency_key`),
  KEY `ix_payments_1` (`checkout_group_id`, `status`, `created_at`),
  KEY `ix_payments_2` (`payer_id`, `paid_at`),
  KEY `ix_payments_order` (`order_id`, `status`, `created_at`),
  CONSTRAINT `ck_payments_1` CHECK (`amount` > 0),
  CONSTRAINT `ck_payments_2` CHECK (`currency` = 'VND'),
  CONSTRAINT `ck_payments_3` CHECK (`status` IN ('PENDING','PROCESSING','PAID','FAILED','REFUNDED','REVERSED','CANCELLED')),
  CONSTRAINT `ck_payments_4` CHECK (`status` <> 'PAID' OR `paid_at` IS NOT NULL),
  CONSTRAINT `ck_payments_fee_rate` CHECK (`platform_fee_rate` >= 0 AND `platform_fee_rate` <= 1),
  CONSTRAINT `ck_payments_fee_amounts` CHECK (`platform_fee` >= 0 AND `seller_amount` >= 0 AND `amount` = `platform_fee` + `seller_amount`),
  CONSTRAINT `fk_payments_1` FOREIGN KEY (`checkout_group_id`) REFERENCES `checkout_groups` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_payments_2` FOREIGN KEY (`payer_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_payments_3` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `shipments` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_id` BIGINT UNSIGNED NOT NULL,
  `carrier` VARCHAR(100) NULL DEFAULT NULL,
  `tracking_code` VARCHAR(150) NULL DEFAULT NULL,
  `shipping_fee` DECIMAL(19,4) NOT NULL DEFAULT 0,
  `status` VARCHAR(20) NOT NULL,
  `shipped_at` DATETIME(3) NULL DEFAULT NULL,
  `delivered_at` DATETIME(3) NULL DEFAULT NULL,
  `currency` CHAR(3) NOT NULL DEFAULT 'VND',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `ix_shipments_1` (`order_id`, `status`),
  KEY `ix_shipments_2` (`tracking_code`),
  CONSTRAINT `ck_shipments_1` CHECK (`shipping_fee` >= 0),
  CONSTRAINT `ck_shipments_2` CHECK (`currency` = 'VND'),
  CONSTRAINT `ck_shipments_3` CHECK (`shipped_at` IS NULL OR `delivered_at` IS NULL OR `delivered_at` >= `shipped_at`),
  CONSTRAINT `fk_shipments_1` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `shipment_tracking` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `shipment_id` BIGINT UNSIGNED NOT NULL,
  `status` VARCHAR(30) NOT NULL,
  `location` VARCHAR(255) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `occurred_at` DATETIME(3) NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `ix_shipment_tracking_1` (`shipment_id`, `occurred_at`, `id`),
  CONSTRAINT `fk_shipment_tracking_1` FOREIGN KEY (`shipment_id`) REFERENCES `shipments` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `returns` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_id` BIGINT UNSIGNED NOT NULL,
  `sale_order_item_id` BIGINT UNSIGNED NOT NULL,
  `reason` VARCHAR(100) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'REQUESTED',
  `requested_by` BIGINT UNSIGNED NOT NULL,
  `requested_at` DATETIME(3) NOT NULL,
  `approved_at` DATETIME(3) NULL DEFAULT NULL,
  `completed_at` DATETIME(3) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `ix_returns_1` (`order_id`, `status`, `requested_at`),
  KEY `ix_returns_2` (`sale_order_item_id`, `status`),
  KEY `ix_returns_3` (`requested_by`),
  CONSTRAINT `fk_returns_1` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_returns_2` FOREIGN KEY (`sale_order_item_id`) REFERENCES `sale_order_items` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_returns_3` FOREIGN KEY (`requested_by`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `refunds` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_id` BIGINT UNSIGNED NOT NULL,
  `payment_id` BIGINT UNSIGNED NOT NULL,
  `sale_order_item_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `borrow_order_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `return_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `requested_by` BIGINT UNSIGNED NULL DEFAULT NULL,
  `provider` VARCHAR(50) NOT NULL,
  `provider_refund_reference` VARCHAR(150) NULL DEFAULT NULL,
  `idempotency_key` VARCHAR(128) NOT NULL,
  `reason` VARCHAR(100) NOT NULL,
  `amount` DECIMAL(19,4) NOT NULL,
  `currency` CHAR(3) NOT NULL DEFAULT 'VND',
  `status` VARCHAR(20) NOT NULL DEFAULT 'REQUESTED',
  `requested_at` DATETIME(3) NOT NULL,
  `approved_at` DATETIME(3) NULL DEFAULT NULL,
  `completed_at` DATETIME(3) NULL DEFAULT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  CONSTRAINT `uq_refunds_1` UNIQUE (`provider`, `provider_refund_reference`),
  CONSTRAINT `uq_refunds_2` UNIQUE (`provider`, `idempotency_key`),
  KEY `ix_refunds_1` (`order_id`, `status`, `created_at`),
  KEY `ix_refunds_2` (`payment_id`, `status`),
  KEY `ix_refunds_3` (`return_id`),
  KEY `ix_refunds_4` (`sale_order_item_id`),
  KEY `ix_refunds_5` (`borrow_order_id`),
  KEY `ix_refunds_6` (`requested_by`),
  CONSTRAINT `ck_refunds_1` CHECK (`amount` > 0),
  CONSTRAINT `ck_refunds_2` CHECK (`currency` = 'VND'),
  CONSTRAINT `fk_refunds_1` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_refunds_2` FOREIGN KEY (`payment_id`) REFERENCES `payments` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_refunds_3` FOREIGN KEY (`sale_order_item_id`) REFERENCES `sale_order_items` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_refunds_4` FOREIGN KEY (`borrow_order_id`) REFERENCES `borrow_orders` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_refunds_5` FOREIGN KEY (`return_id`) REFERENCES `returns` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_refunds_6` FOREIGN KEY (`requested_by`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `favorites` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `book_id` BIGINT UNSIGNED NULL,
  `sale_listing_id` BIGINT UNSIGNED NULL,
  `lend_listing_id` BIGINT UNSIGNED NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  CONSTRAINT `uq_favorites_1` UNIQUE (`user_id`, `book_id`),
  CONSTRAINT `uq_favorites_2` UNIQUE (`user_id`, `sale_listing_id`),
  CONSTRAINT `uq_favorites_3` UNIQUE (`user_id`, `lend_listing_id`),
  KEY `ix_favorites_1` (`user_id`, `created_at`, `id`),
  KEY `ix_favorites_2` (`book_id`),
  KEY `ix_favorites_3` (`sale_listing_id`),
  KEY `ix_favorites_4` (`lend_listing_id`),
  CONSTRAINT `fk_favorites_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_favorites_2` FOREIGN KEY (`book_id`) REFERENCES `books` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_favorites_3` FOREIGN KEY (`sale_listing_id`) REFERENCES `sale_listings` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_favorites_4` FOREIGN KEY (`lend_listing_id`) REFERENCES `lend_listings` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `conversations` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `conversation_type` VARCHAR(20) NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `ix_conversations_1` (`updated_at`, `id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `conversation_members` (
  `conversation_id` BIGINT UNSIGNED NOT NULL,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `joined_at` DATETIME(3) NOT NULL,
  `last_read_at` DATETIME(3) NULL,
  PRIMARY KEY (`conversation_id`, `user_id`),
  KEY `ix_conversation_members_1` (`user_id`, `last_read_at`),
  CONSTRAINT `fk_conversation_members_1` FOREIGN KEY (`conversation_id`) REFERENCES `conversations` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_conversation_members_2` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `messages` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `conversation_id` BIGINT UNSIGNED NOT NULL,
  `sender_id` BIGINT UNSIGNED NOT NULL,
  `message_type` VARCHAR(20) NOT NULL,
  `content` TEXT NOT NULL,
  `attachment_url` VARCHAR(2048) NULL,
  `sent_at` DATETIME(3) NOT NULL,
  `edited_at` DATETIME(3) NULL,
  `deleted_at` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  KEY `ix_messages_1` (`conversation_id`, `sent_at`, `id`),
  KEY `ix_messages_2` (`sender_id`, `sent_at`),
  CONSTRAINT `ck_messages_1` CHECK (`edited_at` IS NULL OR `edited_at` >= `sent_at`),
  CONSTRAINT `ck_messages_2` CHECK (`deleted_at` IS NULL OR `deleted_at` >= `sent_at`),
  CONSTRAINT `fk_messages_1` FOREIGN KEY (`conversation_id`) REFERENCES `conversations` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_messages_2` FOREIGN KEY (`sender_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `notifications` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `notification_type` VARCHAR(50) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `content` TEXT NOT NULL,
  `entity_type` VARCHAR(50) NULL,
  `entity_id` BIGINT UNSIGNED NULL,
  `is_read` BOOLEAN NOT NULL DEFAULT FALSE,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `ix_notifications_1` (`user_id`, `is_read`, `created_at`, `id`),
  CONSTRAINT `ck_notifications_1` CHECK ((`entity_type` IS NULL) = (`entity_id` IS NULL)),
  CONSTRAINT `ck_notifications_2` CHECK (`is_read` IN (0,1)),
  CONSTRAINT `fk_notifications_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `reviews` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `reviewer_id` BIGINT UNSIGNED NOT NULL,
  `order_id` BIGINT UNSIGNED NOT NULL,
  `sale_listing_id` BIGINT UNSIGNED NULL,
  `lend_listing_id` BIGINT UNSIGNED NULL,
  `rating` TINYINT UNSIGNED NOT NULL,
  `comment` TEXT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  CONSTRAINT `uq_reviews_1` UNIQUE (`order_id`, `reviewer_id`),
  KEY `ix_reviews_1` (`sale_listing_id`, `created_at`),
  KEY `ix_reviews_2` (`lend_listing_id`, `created_at`),
  KEY `ix_reviews_3` (`reviewer_id`),
  CONSTRAINT `ck_reviews_2` CHECK (`rating` BETWEEN 1 AND 5),
  CONSTRAINT `fk_reviews_1` FOREIGN KEY (`reviewer_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_reviews_2` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_reviews_3` FOREIGN KEY (`sale_listing_id`) REFERENCES `sale_listings` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_reviews_4` FOREIGN KEY (`lend_listing_id`) REFERENCES `lend_listings` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `reports` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `reporter_id` BIGINT UNSIGNED NOT NULL,
  `reported_user_id` BIGINT UNSIGNED NULL,
  `book_id` BIGINT UNSIGNED NULL,
  `sale_listing_id` BIGINT UNSIGNED NULL,
  `lend_listing_id` BIGINT UNSIGNED NULL,
  `message_id` BIGINT UNSIGNED NULL,
  `reason` VARCHAR(100) NOT NULL,
  `description` TEXT NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'OPEN',
  `handled_by` BIGINT UNSIGNED NULL,
  `resolution_note` TEXT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `resolved_at` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  KEY `ix_reports_1` (`status`, `created_at`),
  KEY `ix_reports_2` (`reported_user_id`, `status`),
  KEY `ix_reports_3` (`reporter_id`),
  KEY `ix_reports_4` (`book_id`),
  KEY `ix_reports_5` (`sale_listing_id`),
  KEY `ix_reports_6` (`lend_listing_id`),
  KEY `ix_reports_7` (`message_id`),
  KEY `ix_reports_8` (`handled_by`),
  CONSTRAINT `fk_reports_1` FOREIGN KEY (`reporter_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_reports_2` FOREIGN KEY (`reported_user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_reports_3` FOREIGN KEY (`book_id`) REFERENCES `books` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_reports_4` FOREIGN KEY (`sale_listing_id`) REFERENCES `sale_listings` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_reports_5` FOREIGN KEY (`lend_listing_id`) REFERENCES `lend_listings` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_reports_6` FOREIGN KEY (`message_id`) REFERENCES `messages` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_reports_7` FOREIGN KEY (`handled_by`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `book_reservations` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `book_id` BIGINT UNSIGNED NOT NULL,
  `requester_id` BIGINT UNSIGNED NOT NULL,
  `owner_id` BIGINT UNSIGNED NOT NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `expires_at` DATETIME(3) NOT NULL,
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `active_book_key` BIGINT UNSIGNED GENERATED ALWAYS AS (CASE WHEN `status` IN ('PENDING','CONFIRMED') THEN `book_id` ELSE NULL END) STORED,
  PRIMARY KEY (`id`),
  CONSTRAINT `uq_book_reservations_active_book` UNIQUE (`active_book_key`),
  KEY `ix_book_reservations_requester` (`requester_id`, `status`, `created_at`),
  KEY `ix_book_reservations_owner` (`owner_id`, `status`, `created_at`),
  KEY `ix_book_reservations_expiry` (`status`, `expires_at`),
  CONSTRAINT `ck_book_reservations_status` CHECK (`status` IN ('PENDING','CONFIRMED','CANCELLED','EXPIRED','COMPLETED','REJECTED')),
  CONSTRAINT `ck_book_reservations_expiry` CHECK (`expires_at` > `created_at`),
  CONSTRAINT `fk_book_reservations_book` FOREIGN KEY (`book_id`) REFERENCES `books` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_book_reservations_requester` FOREIGN KEY (`requester_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_book_reservations_owner` FOREIGN KEY (`owner_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
